### PR TITLE
Update the dependencies to latest descartes and boilerplate

### PR DESCRIPTION
**Pull request by marrts**
Tried to build locally and ran into a few build errors, these fix that.

### CODE REVIEW

**Comment by marrts** [comment]
Not sure why CI isn't running on this one, but it shouldn't actually impact CI at all

**Comment by marip8** [comment]
The CI jobs only run when specific files/directories are changed. This file isn't in that list, so the jobs don't run. Should be okay to merge though

**Comment by marrts** [comment]
Maybe there should be a CI that builds everything from scratch that only runs when this file is changed and then maybe monthly to ensure this is up to date. That way we can guarantee things will build for new users

**Comment by marip8** [comment]
Sounds like a reasonable idea

**Pull request merged**
