### PR TITLE
Feature/visualize colors in scanned sim mesh

### PR DESCRIPTION
**Pull request by DavidSpielman**
Created a function in open3d_sim_node.cpp that takes in a .ply file (it seems to work with a readable ascii format mesh but not with a binary encoded .ply file) and converts it to a visualization_msgs::msg::Marker that appears in Rviz with the colors of the original mesh instead of a single solid color. This works in simulation when there is no camera or robot data.

### CODE REVIEW

**Comment by marip8** [comment]
I wonder if using a package for visualizing meshes (specifically `pcl_msgs/PolygonMesh`) with per-vertex coloring [like this](https://github.com/marip8/colorized_mesh_display) would be a better approach

**Comment by DavidSpielman** [comment]
Is the colorized mesh display package less sensitive to the file type of the input mesh?

**Comment by marip8** [comment]
It just knows how to display a `pcl_msgs/PolygonMesh`, which is roughly equivalent to `pcl::PolygonMesh`, so it doesn't really matter what the mesh file extension is, provided it is something that can be converted into a `pcl::PolygonMesh`

**Comment by marip8** [comment]
Closing; addressed in #58 and #64

**Pull request closed without merging**
